// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/sfu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SdpType int32

const (
	SdpType_SDP_TYPE_UNSPECIFIED SdpType = 0
	SdpType_OFFER                SdpType = 1
	SdpType_ANSWER               SdpType = 2
)

// Enum value maps for SdpType.
var (
	SdpType_name = map[int32]string{
		0: "SDP_TYPE_UNSPECIFIED",
		1: "OFFER",
		2: "ANSWER",
	}
	SdpType_value = map[string]int32{
		"SDP_TYPE_UNSPECIFIED": 0,
		"OFFER":                1,
		"ANSWER":               2,
	}
)

func (x SdpType) Enum() *SdpType {
	p := new(SdpType)
	*p = x
	return p
}

func (x SdpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdpType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_sfu_proto_enumTypes[0].Descriptor()
}

func (SdpType) Type() protoreflect.EnumType {
	return &file_api_proto_sfu_proto_enumTypes[0]
}

func (x SdpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdpType.Descriptor instead.
func (SdpType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_sfu_proto_rawDescGZIP(), []int{0}
}

// Session Description (SDP)
type SDP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SdpType                `protobuf:"varint,1,opt,name=type,proto3,enum=SFU.SdpType" json:"type,omitempty"`
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SDP) Reset() {
	*x = SDP{}
	mi := &file_api_proto_sfu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDP) ProtoMessage() {}

func (x *SDP) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sfu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDP.ProtoReflect.Descriptor instead.
func (*SDP) Descriptor() ([]byte, []int) {
	return file_api_proto_sfu_proto_rawDescGZIP(), []int{0}
}

func (x *SDP) GetType() SdpType {
	if x != nil {
		return x.Type
	}
	return SdpType_SDP_TYPE_UNSPECIFIED
}

func (x *SDP) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type IceCandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex    uint32                 `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_api_proto_sfu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sfu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_api_proto_sfu_proto_rawDescGZIP(), []int{1}
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *IceCandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *IceCandidate) GetSdpMlineIndex() uint32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *IceCandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

type PeerSignal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PeerSignal_Sdp
	//	*PeerSignal_Ice
	Payload       isPeerSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSignal) Reset() {
	*x = PeerSignal{}
	mi := &file_api_proto_sfu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSignal) ProtoMessage() {}

func (x *PeerSignal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sfu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSignal.ProtoReflect.Descriptor instead.
func (*PeerSignal) Descriptor() ([]byte, []int) {
	return file_api_proto_sfu_proto_rawDescGZIP(), []int{2}
}

func (x *PeerSignal) GetPayload() isPeerSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PeerSignal) GetSdp() *SDP {
	if x != nil {
		if x, ok := x.Payload.(*PeerSignal_Sdp); ok {
			return x.Sdp
		}
	}
	return nil
}

func (x *PeerSignal) GetIce() *IceCandidate {
	if x != nil {
		if x, ok := x.Payload.(*PeerSignal_Ice); ok {
			return x.Ice
		}
	}
	return nil
}

type isPeerSignal_Payload interface {
	isPeerSignal_Payload()
}

type PeerSignal_Sdp struct {
	Sdp *SDP `protobuf:"bytes,1,opt,name=sdp,proto3,oneof"`
}

type PeerSignal_Ice struct {
	Ice *IceCandidate `protobuf:"bytes,2,opt,name=ice,proto3,oneof"`
}

func (*PeerSignal_Sdp) isPeerSignal_Payload() {}

func (*PeerSignal_Ice) isPeerSignal_Payload() {}

var File_api_proto_sfu_proto protoreflect.FileDescriptor

const file_api_proto_sfu_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/sfu.proto\x12\x03SFU\"9\n" +
	"\x03SDP\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.SFU.SdpTypeR\x04type\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\"\x9a\x01\n" +
	"\fIceCandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\rR\rsdpMlineIndex\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"\\\n" +
	"\n" +
	"PeerSignal\x12\x1c\n" +
	"\x03sdp\x18\x01 \x01(\v2\b.SFU.SDPH\x00R\x03sdp\x12%\n" +
	"\x03ice\x18\x02 \x01(\v2\x11.SFU.IceCandidateH\x00R\x03iceB\t\n" +
	"\apayload*:\n" +
	"\aSdpType\x12\x18\n" +
	"\x14SDP_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05OFFER\x10\x01\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x0225\n" +
	"\x03SFU\x12.\n" +
	"\x06Signal\x12\x0f.SFU.PeerSignal\x1a\x0f.SFU.PeerSignal(\x010\x01B\fZ\n" +
	"api/proto/b\x06proto3"

var (
	file_api_proto_sfu_proto_rawDescOnce sync.Once
	file_api_proto_sfu_proto_rawDescData []byte
)

func file_api_proto_sfu_proto_rawDescGZIP() []byte {
	file_api_proto_sfu_proto_rawDescOnce.Do(func() {
		file_api_proto_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sfu_proto_rawDesc), len(file_api_proto_sfu_proto_rawDesc)))
	})
	return file_api_proto_sfu_proto_rawDescData
}

var file_api_proto_sfu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_sfu_proto_goTypes = []any{
	(SdpType)(0),         // 0: SFU.SdpType
	(*SDP)(nil),          // 1: SFU.SDP
	(*IceCandidate)(nil), // 2: SFU.IceCandidate
	(*PeerSignal)(nil),   // 3: SFU.PeerSignal
}
var file_api_proto_sfu_proto_depIdxs = []int32{
	0, // 0: SFU.SDP.type:type_name -> SFU.SdpType
	1, // 1: SFU.PeerSignal.sdp:type_name -> SFU.SDP
	2, // 2: SFU.PeerSignal.ice:type_name -> SFU.IceCandidate
	3, // 3: SFU.SFU.Signal:input_type -> SFU.PeerSignal
	3, // 4: SFU.SFU.Signal:output_type -> SFU.PeerSignal
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_sfu_proto_init() }
func file_api_proto_sfu_proto_init() {
	if File_api_proto_sfu_proto != nil {
		return
	}
	file_api_proto_sfu_proto_msgTypes[2].OneofWrappers = []any{
		(*PeerSignal_Sdp)(nil),
		(*PeerSignal_Ice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sfu_proto_rawDesc), len(file_api_proto_sfu_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sfu_proto_goTypes,
		DependencyIndexes: file_api_proto_sfu_proto_depIdxs,
		EnumInfos:         file_api_proto_sfu_proto_enumTypes,
		MessageInfos:      file_api_proto_sfu_proto_msgTypes,
	}.Build()
	File_api_proto_sfu_proto = out.File
	file_api_proto_sfu_proto_goTypes = nil
	file_api_proto_sfu_proto_depIdxs = nil
}
