// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/sfu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SFU_Signal_FullMethodName = "/SFU.SFU/Signal"
)

// SFUClient is the client API for SFU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SFUClient interface {
	Signal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PeerSignal, PeerSignal], error)
}

type sFUClient struct {
	cc grpc.ClientConnInterface
}

func NewSFUClient(cc grpc.ClientConnInterface) SFUClient {
	return &sFUClient{cc}
}

func (c *sFUClient) Signal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PeerSignal, PeerSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SFU_ServiceDesc.Streams[0], SFU_Signal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PeerSignal, PeerSignal]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SFU_SignalClient = grpc.BidiStreamingClient[PeerSignal, PeerSignal]

// SFUServer is the server API for SFU service.
// All implementations must embed UnimplementedSFUServer
// for forward compatibility.
type SFUServer interface {
	Signal(grpc.BidiStreamingServer[PeerSignal, PeerSignal]) error
	mustEmbedUnimplementedSFUServer()
}

// UnimplementedSFUServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSFUServer struct{}

func (UnimplementedSFUServer) Signal(grpc.BidiStreamingServer[PeerSignal, PeerSignal]) error {
	return status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSFUServer) mustEmbedUnimplementedSFUServer() {}
func (UnimplementedSFUServer) testEmbeddedByValue()             {}

// UnsafeSFUServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SFUServer will
// result in compilation errors.
type UnsafeSFUServer interface {
	mustEmbedUnimplementedSFUServer()
}

func RegisterSFUServer(s grpc.ServiceRegistrar, srv SFUServer) {
	// If the following call pancis, it indicates UnimplementedSFUServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SFU_ServiceDesc, srv)
}

func _SFU_Signal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SFUServer).Signal(&grpc.GenericServerStream[PeerSignal, PeerSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SFU_SignalServer = grpc.BidiStreamingServer[PeerSignal, PeerSignal]

// SFU_ServiceDesc is the grpc.ServiceDesc for SFU service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SFU_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SFU.SFU",
	HandlerType: (*SFUServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Signal",
			Handler:       _SFU_Signal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/sfu.proto",
}
